const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('atlasBrowser', {
  activateBrowserContext: (context) => ipcRenderer.send('atlas:browser-activate', context),
  syncBrowserContexts: (contexts) => ipcRenderer.send('atlas:browser-sync', contexts),
  navigate: (request) => ipcRenderer.send('atlas:navigate', request),
  back: (context) => ipcRenderer.send('atlas:back', context),
  forward: (context) => ipcRenderer.send('atlas:forward', context),
  reload: (context) => ipcRenderer.send('atlas:reload', context),
  showAppMenu: () => ipcRenderer.send('atlas:show-app-menu'),
  setBounds: (bounds) => ipcRenderer.send('atlas:bounds', bounds),
  onNavigated: (callback) => ipcRenderer.on('atlas:navigated', (_event, url) => callback(url)),
  onTitle: (callback) => ipcRenderer.on('atlas:title', (_event, title) => callback(title)),
  onFavicon: (callback) => ipcRenderer.on('atlas:favicon', (_event, favicon) => callback(favicon)),
  onSiteHealth: (callback) => ipcRenderer.on('atlas:site-health', (_event, status) => callback(status)),
  onSendSelectionToLibrary: (callback) => ipcRenderer.on('atlas:send-selection-to-library', (_event, payload) => callback(payload)),
  onAppCommand: (callback) => ipcRenderer.on('atlas:app-command', (_event, command) => callback(command)),
  getAgentStatus: () => ipcRenderer.invoke('atlas:agent-status'),
  getCodexRateLimits: () => ipcRenderer.invoke('atlas:codex-rate-limits'),
  getAgentUsage: () => ipcRenderer.invoke('atlas:agent-usage'),
  getAgentProviderTemplates: () => ipcRenderer.invoke('atlas:agent-provider-templates'),
  configureAgentProvider: (config) => ipcRenderer.invoke('atlas:agent-provider-configure', config),
  testAgentProvider: () => ipcRenderer.invoke('atlas:agent-provider-test'),
  loginAgentProvider: () => ipcRenderer.invoke('atlas:agent-provider-login'),
  saveAgentProviderSecret: (payload) => ipcRenderer.invoke('atlas:agent-provider-secret', payload),
  createAgentThread: () => ipcRenderer.invoke('atlas:agent-create-thread'),
  sendAgentTurn: (payload) => ipcRenderer.invoke('atlas:agent-send', payload),
  readAgentThread: (threadId) => ipcRenderer.invoke('atlas:agent-read-thread', threadId),
  compactAgentThread: (threadId) => ipcRenderer.invoke('atlas:agent-compact-thread', threadId),
  deleteAgentThread: (threadId) => ipcRenderer.invoke('atlas:agent-delete-thread', threadId),
  readCurrentPage: (options) => ipcRenderer.invoke('atlas:read-current-page', options),
  inspectPage: (options) => ipcRenderer.invoke('atlas:browser-inspect', options),
  clickPage: (options) => ipcRenderer.invoke('atlas:browser-click', options),
  typePage: (options) => ipcRenderer.invoke('atlas:browser-type', options),
  pressPageKey: (options) => ipcRenderer.invoke('atlas:browser-press-key', options),
  scrollPage: (options) => ipcRenderer.invoke('atlas:browser-scroll', options),
  setDownloadContext: (context) => ipcRenderer.send('atlas:download-context', context),
  setLibraryFileLinks: (links) => ipcRenderer.send('atlas:library-file-links', links),
  readLibraryFile: (options) => ipcRenderer.invoke('atlas:library-file-read', options),
  getLibraryFileStatus: (options) => ipcRenderer.invoke('atlas:library-file-status', options),
  openLibraryFile: (options) => ipcRenderer.invoke('atlas:library-file-open', options),
  openDownloadedFile: (downloadPath) => ipcRenderer.invoke('atlas:download-open', downloadPath),
  onDownloadEvent: (callback) => ipcRenderer.on('atlas:download-event', (_event, download) => callback(download)),
  getPrivacyStatus: (profileId) => ipcRenderer.invoke('atlas:privacy-status', profileId),
  setPrivacyMode: (request) => ipcRenderer.invoke('atlas:privacy-mode', request),
  clearWebsiteData: (profileId) => ipcRenderer.invoke('atlas:clear-website-data', profileId),
  setWebsiteMediaPermissions: (request) => ipcRenderer.invoke('atlas:website-media-permissions', request),
  onPrivacyStatus: (callback) => ipcRenderer.on('atlas:privacy-status', (_event, status) => callback(status)),
  transcribeAudio: (payload) => ipcRenderer.invoke('atlas:transcribe-audio', payload),
  extractPdfText: (bytes) => ipcRenderer.invoke('atlas:extract-pdf-text', bytes),
  getTtsVoices: () => ipcRenderer.invoke('atlas:tts-voices'),
  synthesizeSpeech: (payload) => ipcRenderer.invoke('atlas:synthesize-speech', payload),
  cancelSpeech: () => ipcRenderer.invoke('atlas:cancel-speech'),
  onAgentEvent: (callback) => ipcRenderer.on('atlas:agent-event', (_event, message) => callback(message)),
  onAgentToolRequest: (callback) => ipcRenderer.on('atlas:agent-tool-request', (_event, request) => callback(request)),
  resolveAgentTool: (payload) => ipcRenderer.send('atlas:agent-tool-result', payload)
});
