const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('atlasBrowser', {
  navigate: (url) => ipcRenderer.send('atlas:navigate', url),
  back: () => ipcRenderer.send('atlas:back'),
  forward: () => ipcRenderer.send('atlas:forward'),
  reload: () => ipcRenderer.send('atlas:reload'),
  showAppMenu: () => ipcRenderer.send('atlas:show-app-menu'),
  setBounds: (bounds) => ipcRenderer.send('atlas:bounds', bounds),
  onNavigated: (callback) => ipcRenderer.on('atlas:navigated', (_event, url) => callback(url)),
  onTitle: (callback) => ipcRenderer.on('atlas:title', (_event, title) => callback(title)),
  onFavicon: (callback) => ipcRenderer.on('atlas:favicon', (_event, favicon) => callback(favicon)),
  onSiteHealth: (callback) => ipcRenderer.on('atlas:site-health', (_event, status) => callback(status)),
  onSendSelectionToLibrary: (callback) => ipcRenderer.on('atlas:send-selection-to-library', (_event, payload) => callback(payload)),
  onAppCommand: (callback) => ipcRenderer.on('atlas:app-command', (_event, command) => callback(command)),
  getAgentStatus: () => ipcRenderer.invoke('atlas:agent-status'),
  getCodexRateLimits: () => ipcRenderer.invoke('atlas:codex-rate-limits'),
  getAgentUsage: () => ipcRenderer.invoke('atlas:agent-usage'),
  getAgentProviderTemplates: () => ipcRenderer.invoke('atlas:agent-provider-templates'),
  configureAgentProvider: (config) => ipcRenderer.invoke('atlas:agent-provider-configure', config),
  testAgentProvider: () => ipcRenderer.invoke('atlas:agent-provider-test'),
  loginAgentProvider: () => ipcRenderer.invoke('atlas:agent-provider-login'),
  saveAgentProviderSecret: (payload) => ipcRenderer.invoke('atlas:agent-provider-secret', payload),
  createAgentThread: () => ipcRenderer.invoke('atlas:agent-create-thread'),
  sendAgentTurn: (payload) => ipcRenderer.invoke('atlas:agent-send', payload),
  readAgentThread: (threadId) => ipcRenderer.invoke('atlas:agent-read-thread', threadId),
  compactAgentThread: (threadId) => ipcRenderer.invoke('atlas:agent-compact-thread', threadId),
  deleteAgentThread: (threadId) => ipcRenderer.invoke('atlas:agent-delete-thread', threadId),
  readCurrentPage: () => ipcRenderer.invoke('atlas:read-current-page'),
  getPrivacyStatus: () => ipcRenderer.invoke('atlas:privacy-status'),
  setPrivacyMode: (mode) => ipcRenderer.invoke('atlas:privacy-mode', mode),
  clearWebsiteData: () => ipcRenderer.invoke('atlas:clear-website-data'),
  onPrivacyStatus: (callback) => ipcRenderer.on('atlas:privacy-status', (_event, status) => callback(status)),
  transcribeAudio: (payload) => ipcRenderer.invoke('atlas:transcribe-audio', payload),
  extractPdfText: (bytes) => ipcRenderer.invoke('atlas:extract-pdf-text', bytes),
  getTtsVoices: () => ipcRenderer.invoke('atlas:tts-voices'),
  synthesizeSpeech: (payload) => ipcRenderer.invoke('atlas:synthesize-speech', payload),
  onAgentEvent: (callback) => ipcRenderer.on('atlas:agent-event', (_event, message) => callback(message)),
  onAgentToolRequest: (callback) => ipcRenderer.on('atlas:agent-tool-request', (_event, request) => callback(request)),
  resolveAgentTool: (payload) => ipcRenderer.send('atlas:agent-tool-result', payload)
});
